### ISSUE TITLE
各indexファイルの編集

### ISSUE THREAD

**Issue by munepi** [texjporg/w32texorg-static#1]
日本語、英語、中国語の各indexファイルの先頭に、

 * W32TeX公式サイトが2021/06/24を最終更新で閉じた旨
 * W32TeXを恒久的に保管する旨

を加筆していただけませんでしょうか？
文面案がある方がいらっしゃったら、ぜひお願いしたいです。
（中国語 index-zh.html は、英語でも良いと思います）

また、https://texlive.texjp.org/2021/w32tex/ 配下にすべてのファイルがself-containedしましたので、
各所にリンクを張っている箇所、記述は、
https://texlive.texjp.org/2021/w32tex/ 配下に直してしまってよいと思います。
（RINGサーバ上のW32TeXのarchiveもおそらく恒久的に残されるだろうと思います）

--------

あるいは、バッサリと「archiveである旨」を README.txt 一文だけ加えておくだけにしてしまう手もあります！
各htmlファイルをブラウザで見たとき、テキストファイルとして表示させてしまうようにしてしまえば、それで十分だと思います。

**Comment by munepi** [comment]
ringサーバへリンクをが貼られているファイルは、ringサーバにW32TeXのアーカイブが残っているかぎり、そのままでも良いかもしれません。

**Comment by kuroky49** [comment]
着手します．

**Comment by kuroky49** [comment]
ブランチを切って，手元での修正は終わったのですが，

```
fatal: unable to access 'https://github.com/texjporg/w32texorg-static.git/': Could not resolve host: github.com
```

と言われて push できないところではまってしまいました．https からの push は許可していないんでしたっけ？ @munepi

**Comment by munepi** [comment]
おそらく、httpsでgit cloneしてしまっていると思うので、
黒木さんお手元の同ディレクトリにある `.git/config` で以下の箇所

```
[remote "origin"]
    url = https://github.com/texjporg/w32texorg-static.git
    fetch = +refs/heads/*:refs/remotes/origin/*
```

を

```
[remote "origin"]
    url = git@github.com:texjporg/w32texorg-static.git
    fetch = +refs/heads/*:refs/remotes/origin/*
```

に書き換えると、（黒木さんのGitHubの kuroky49 アカウントに対して、正しく公開鍵が登録されていれば、）問題なく `git push`できるはずです。
